### ISSUE TITLE
Commit Messages with Quotes Fail to Parse

### ISSUE THREAD

**Issue by martindale** [gordonwritescode/gitty#32]
```bash
l.com>","date": "Wed Aug 6 17:17:01 2014 -0700","message": "Revert "Revert \"p
                                                                    ^
SyntaxError: Unexpected token R
    at Object.parse (native)
    at Object.parsers.log (/opt/shipright/node_modules/gitty/modules/output-parser.js:36:17)
    at /opt/shipright/node_modules/gitty/classes/repository.js:82:28
    at ChildProcess.exithandler (child_process.js:644:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

**Comment by gordonwritescode** [comment]
I'll pick this up again

**Comment by musbaig** [comment]
Any traction or updates on this issue?
