### ISSUE TITLE
Error: Cannot find module './build/Release/shell'

### ISSUE THREAD

**Issue by interist32** [gordonwritescode/gitty#43]
After node.js update to 0.12.0 I've got this Error message:

module.js:338
    throw err;
          ^
Error: Cannot find module './build/Release/shell'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/makushev/i32utils/colibs/node_modules/gitty/node_modules/execSync/index.js:30:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

I tried remove node and npm and then to start from scratch. But still have this issue;

When I start with npm install, a I get next error message:
execSync@1.0.2 install /Users/qwerty/i32utils/colibs/node_modules/gitty/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!

I supposed that execSync is not supported in node 0.12. They say that you have to use exec-sync instead (https://github.com/mgutz/execSync/issues/27).

**Comment by gordonwritescode** [comment]
Gitty v3.2.0 no longer depends on `execSync` - using the native `child_process.execSync` instead (though Node 0.12.0 is now a prerequisite)
